### PR TITLE
Add support for Cocoapods

### PR DESCRIPTION
**Pull request by chrislconover**
I added support for Cocoapods in order to import it into a framework of my own.

I left instructions in the README, so this commit will need some TLC to run the publish command and then remove the aforementioned instructions.

### CODE REVIEW

**Comment by sbooth** [comment]
Thank you for submitting this PR.

I don't use CocoaPods but if I'm understanding the docs correctly, in order to publish a pod the .podspec has to be present in the repo under the appropriate version tag. Is that correct? If so I'm wondering how best to handle versioning since I attempt to track the geographiclib version numbers for simplicity's sake. Perhaps using a semver build would work but I'm not sure if that's supported by CocoaPods either.

**Comment by chrislconover** [comment]
Apologies for the delay. 

I have never published a podspec, but to the best of my knowledge, the versioning you have should suffice. 

Honestly, the process seems a little convoluted - how do you test before pushing the spec file to your repo? That said, I have it working both locally and from my repo, the final step is to add it to the master index, presumably after you merge the podspecs to your repo.  I did get some linting errors though (`pod spec lint`) - you just had one set of copy for title & description.

Backing out a level though, you could update the aforementioned copy, merge it to your repo without doing any harm. The issue is that since you have one library depending on another, you need to publish your podspec for at lest your CGeodesic library, for the interdependency to work. I worked around that by using a bit of a hack to tell it about `CGeodesic`  before importing`Geodesic`.
 
For reference, my app's podfile (that defines the dependency on your library) looks like:

```
use_frameworks!

platform :ios, '17.0'

target 'MyApp' do
    project 'MyApp'
    
     # hack to tell the system where to find the depency
    pod 'CGeodesic', :git => 'https://github.com/chrislconover/CGeodesic.git'
    
    # the normal entry to that points directly to the (in this case my fork)
    pod 'Geodesic', :git => 'https://github.com/chrislconover/Geodesic.git'    
end
```

It should however, look like this:

```
target 'MyApp' do
    project 'MyApp'
    
    # finds the registered Geodesic podspec, which depends on the registered CGeodesic podspec
    pod 'Geodesic'
end
```

I haven't done public merges, but my work should really be on a branch on your end, for you to test and then merge. I'm not super sure how do that.

Cheers

**Comment by chrislconover** [comment]
At the very least, merging the podspec files into your repo would allow people to use my work around, while catching any updates that you might make to your repo.  Publishing the podspec makes the whole process seamless to the consumer. :-)

**Comment by sbooth** [comment]
I merged a branch containing a podspec into `main`. I'll work on having it added to the official cocoapods repo.

**Pull request closed without merging**
